/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bootstrap/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bootstrapStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHosts"];
        put?: never;
        post: operations["createHost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{host_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        get: operations["getHost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateHost"];
        trace?: never;
    };
    "/api/v1/hosts/{host_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disableHost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{host_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enableHost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{host_id}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        get: operations["listHostAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{host_id}/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        get: operations["getHostInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{host_id}/enrollment-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        get: operations["listEnrollmentTokens"];
        put?: never;
        post: operations["createEnrollmentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollment-tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: components["parameters"]["TokenId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeEnrollmentToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-enrollment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enrollAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStorageCredentials"];
        put?: never;
        post: operations["createStorageCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage-credentials/{credential_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        get: operations["getStorageCredential"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage-credentials/{credential_id}/replace-secret": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replaceStorageCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage-credentials/{credential_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disableStorageCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StorageCredential: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            provider: "RCLONE_ONEDRIVE";
            remote_name: string;
            /** @enum {string} */
            status: "UNTESTED" | "HEALTHY" | "DEGRADED" | "EXPIRED" | "DISABLED";
            /** Format: int64 */
            secret_revision: number;
            /** Format: int64 */
            revision: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        StorageCredentialList: {
            items: components["schemas"]["StorageCredential"][];
            next_cursor?: string;
        };
        StorageCredentialCreate: {
            name: string;
            remote_name: string;
            /** @description Restricted OneDrive + Crypt configuration, at most 256 KiB UTF-8. */
            rclone_config: string;
        };
        StorageCredentialReplace: {
            /** @description Token/client credential replacement; storage target and Crypt settings must remain identical. */
            rclone_config: string;
        };
        BootstrapStatus: {
            bootstrap_required: boolean;
        };
        BootstrapRequest: {
            username: string;
            display_name: string;
            password: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        Session: {
            user: components["schemas"]["User"];
            /** Format: date-time */
            idle_expires_at: string;
            /** Format: date-time */
            absolute_expires_at: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name: string;
            /** @enum {string} */
            role: "ADMIN" | "VIEWER";
        };
        DashboardSummary: {
            /** Format: date-time */
            collected_at: string;
            /** Format: int64 */
            hosts: number;
            /** Format: int64 */
            agents_online: number;
            /** Format: int64 */
            agents_degraded: number;
            /** Format: int64 */
            agents_offline: number;
            /** Format: int64 */
            plans: number;
            /** Format: int64 */
            repositories: number;
            /** Format: int64 */
            operations: number;
        };
        Version: {
            version: string;
            commit: string;
            built_at: string;
            schema_version: number;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            checks?: {
                [key: string]: string;
            };
        };
        Host: {
            /** Format: uuid */
            id: string;
            display_name: string;
            description: string;
            labels: {
                [key: string]: string;
            };
            timezone: string;
            /** @enum {string} */
            status: "PENDING" | "ACTIVE" | "DISABLED" | "REVOKED";
            /** Format: int64 */
            revision: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        HostList: {
            items: components["schemas"]["Host"][];
        };
        HostCreate: {
            display_name: string;
            /** @default  */
            description: string;
            labels?: {
                [key: string]: string;
            };
            timezone: string;
        };
        HostPatch: {
            display_name?: string;
            description?: string;
            labels?: {
                [key: string]: string;
            };
            timezone?: string;
        };
        Agent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            host_id: string;
            /** Format: uuid */
            install_id: string;
            public_key_fingerprint: string;
            certificate_serial: string;
            /** Format: date-time */
            certificate_not_after: string;
            /** @enum {string} */
            status: "ACTIVE" | "REVOKED";
            /** @enum {string} */
            health: "ONLINE" | "DEGRADED" | "OFFLINE" | "REVOKED";
            version: string;
            protocol_version: string;
            os: string;
            arch: string;
            hostname: string;
            boot_id?: string;
            restic_version?: string;
            /** Format: date-time */
            last_seen_at?: string;
            /** Format: date-time */
            last_connected_at?: string;
            /** Format: int64 */
            desired_revision: number;
            /** Format: int64 */
            accepted_revision: number;
            /** Format: int64 */
            uptime_seconds: number;
            /** Format: int64 */
            state_free_bytes: number;
            /** Format: int64 */
            clock_offset_ms: number;
            heartbeat_error_code: string;
            config_error_code: string;
            config_error_field: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AgentInventory: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            agent_id: string;
            /** Format: date-time */
            captured_at: string;
            kernel: string;
            os_release: string;
            /** @enum {string} */
            cpu_arch: "amd64" | "arm64";
            agent_version: string;
            restic_version: string;
            containerized: boolean;
            available_bytes: {
                [key: string]: number;
            };
            /** Format: int64 */
            clock_offset_ms: number;
            capabilities: string[];
        };
        AgentList: {
            items: components["schemas"]["Agent"][];
        };
        EnrollmentTokenCreate: {
            /** @default 600 */
            expires_in_seconds: number;
        };
        EnrollmentInstall: {
            native: string;
            docker: string;
        };
        EnrollmentTokenCreated: {
            /** Format: uuid */
            id: string;
            token: string;
            fingerprint: string;
            /** Format: date-time */
            expires_at: string;
            install: components["schemas"]["EnrollmentInstall"];
        };
        EnrollmentToken: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            host_id: string;
            fingerprint: string;
            /** @enum {string} */
            status: "ACTIVE" | "USED" | "EXPIRED" | "REVOKED";
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            used_at?: string;
            /** Format: uuid */
            used_by_agent_id?: string;
            /** Format: date-time */
            revoked_at?: string;
        };
        EnrollmentTokenList: {
            items: components["schemas"]["EnrollmentToken"][];
        };
        AgentEnrollmentRequest: {
            token: string;
            csr_pem: string;
            /** Format: uuid */
            install_id: string;
            agent_version: string;
            protocol_version: string;
            hostname: string;
            /** @enum {string} */
            os: "linux";
            /** @enum {string} */
            arch: "amd64" | "arm64";
            capabilities: string[];
        };
        AgentEnrollmentResponse: {
            /** Format: uuid */
            agent_id: string;
            /** Format: uuid */
            host_id: string;
            certificate_pem: string;
            ca_bundle_pem: string;
            /** Format: date-time */
            not_after: string;
            server_name: string;
            grpc_endpoint: string;
            heartbeat_interval_seconds: number;
        };
        AgentRevoke: {
            reason: string;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance: string;
            code: string;
            /** Format: uuid */
            request_id: string;
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            field: string;
            code: string;
        };
    };
    responses: {
        /** @description RFC 9457 problem response. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        HostId: string;
        AgentId: string;
        TokenId: string;
        IfMatch: string;
        IdempotencyKey: string;
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Required dependencies are ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    bootstrapStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether the first administrator must be created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapStatus"];
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    bootstrap: {
        parameters: {
            query?: never;
            header: {
                "X-RestFleet-Bootstrap-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapRequest"];
            };
        };
        responses: {
            /** @description First administrator and authenticated session created. */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated session created. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookies cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    dashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empty-capable control-plane summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build and compatible schema version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listHosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hosts visible to the current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostList"];
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    createHost: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostCreate"];
            };
        };
        responses: {
            /** @description Host created in PENDING state. */
            201: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Host"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getHost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host detail. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Host"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    updateHost: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostPatch"];
            };
        };
        responses: {
            /** @description Host updated. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Host"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    disableHost: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host disabled. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Host"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    enableHost: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host enabled. */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Host"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listHostAgents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent identities associated with the Host. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentList"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getHostInventory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest inventory reported by an Agent associated with the Host. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentInventory"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listEnrollmentTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrollment token metadata. Bearer tokens are never returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTokenList"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    createEnrollmentToken: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                host_id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentTokenCreate"];
            };
        };
        responses: {
            /** @description Enrollment token created. The bearer value appears only in this response. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentTokenCreated"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    revokeEnrollmentToken: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                token_id: components["parameters"]["TokenId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unused enrollment token revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    enrollAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentEnrollmentRequest"];
            };
        };
        responses: {
            /** @description Agent identity bundle. The private key is never returned. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEnrollmentResponse"];
                };
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent identity and connection metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    revokeAgent: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRevoke"];
            };
        };
        responses: {
            /** @description Agent and all currently valid certificates revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listStorageCredentials: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata only. Secrets and ciphertext are never returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageCredentialList"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    createStorageCredential: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageCredentialCreate"];
            };
        };
        responses: {
            /** @description Imported and encrypted; UNTESTED does not indicate remote connectivity. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageCredential"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getStorageCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential metadata; ETag contains the resource revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageCredential"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    replaceStorageCredential: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageCredentialReplace"];
            };
        };
        responses: {
            /** @description Credential metadata; ETag contains the new revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageCredential"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    disableStorageCredential: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential metadata; ETag contains the new revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageCredential"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
}
