//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthStatus.
const (
	Ok          HealthStatus = "ok"
	Unavailable HealthStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	ADMIN  UserRole = "ADMIN"
	VIEWER UserRole = "VIEWER"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case ADMIN:
		return true
	case VIEWER:
		return true
	default:
		return false
	}
}

// BootstrapRequest defines model for BootstrapRequest.
type BootstrapRequest struct {
	DisplayName string `json:"display_name"`
	Password    string `json:"password"`
	Username    string `json:"username"`
}

// BootstrapStatus defines model for BootstrapStatus.
type BootstrapStatus struct {
	BootstrapRequired bool `json:"bootstrap_required"`
}

// DashboardSummary defines model for DashboardSummary.
type DashboardSummary struct {
	CollectedAt  time.Time `json:"collected_at"`
	Hosts        int64     `json:"hosts"`
	Operations   int64     `json:"operations"`
	Plans        int64     `json:"plans"`
	Repositories int64     `json:"repositories"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Code  string `json:"code"`
	Field string `json:"field"`
}

// Health defines model for Health.
type Health struct {
	Checks *map[string]string `json:"checks,omitempty"`
	Status HealthStatus       `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Problem defines model for Problem.
type Problem struct {
	Code      string             `json:"code"`
	Detail    string             `json:"detail"`
	Errors    *[]FieldError      `json:"errors,omitempty"`
	Instance  string             `json:"instance"`
	RequestId openapi_types.UUID `json:"request_id"`
	Status    int                `json:"status"`
	Title     string             `json:"title"`
	Type      string             `json:"type"`
}

// Session defines model for Session.
type Session struct {
	AbsoluteExpiresAt time.Time `json:"absolute_expires_at"`
	IdleExpiresAt     time.Time `json:"idle_expires_at"`
	User              User      `json:"user"`
}

// User defines model for User.
type User struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Role        UserRole           `json:"role"`
	Username    string             `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// Version defines model for Version.
type Version struct {
	BuiltAt       string `json:"built_at"`
	Commit        string `json:"commit"`
	SchemaVersion int    `json:"schema_version"`
	Version       string `json:"version"`
}

// CsrfToken defines model for CsrfToken.
type CsrfToken = string

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// BootstrapParams defines parameters for Bootstrap.
type BootstrapParams struct {
	XRestFleetBootstrapToken string `json:"X-RestFleet-Bootstrap-Token"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// BootstrapJSONRequestBody defines body for Bootstrap for application/json ContentType.
type BootstrapJSONRequestBody = BootstrapRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request, params LogoutParams)

	// (GET /api/v1/auth/session)
	Session(w http.ResponseWriter, r *http.Request)

	// (POST /api/v1/bootstrap)
	Bootstrap(w http.ResponseWriter, r *http.Request, params BootstrapParams)

	// (GET /api/v1/bootstrap/status)
	BootstrapStatus(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/dashboard/summary)
	DashboardSummary(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/version)
	Version(w http.ResponseWriter, r *http.Request)

	// (GET /health/live)
	HealthLive(w http.ResponseWriter, r *http.Request)

	// (GET /health/ready)
	HealthReady(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	headers := r.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		err := fmt.Errorf("Header parameter X-CSRF-Token is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-CSRF-Token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Session operation middleware
func (siw *ServerInterfaceWrapper) Session(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Session(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Bootstrap operation middleware
func (siw *ServerInterfaceWrapper) Bootstrap(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params BootstrapParams

	headers := r.Header

	// ------------- Required header parameter "X-RestFleet-Bootstrap-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-RestFleet-Bootstrap-Token")]; found {
		var XRestFleetBootstrapToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-RestFleet-Bootstrap-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-RestFleet-Bootstrap-Token", valueList[0], &XRestFleetBootstrapToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-RestFleet-Bootstrap-Token", Err: err})
			return
		}

		params.XRestFleetBootstrapToken = XRestFleetBootstrapToken

	} else {
		err := fmt.Errorf("Header parameter X-RestFleet-Bootstrap-Token is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-RestFleet-Bootstrap-Token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Bootstrap(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BootstrapStatus operation middleware
func (siw *ServerInterfaceWrapper) BootstrapStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BootstrapStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DashboardSummary operation middleware
func (siw *ServerInterfaceWrapper) DashboardSummary(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DashboardSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Version operation middleware
func (siw *ServerInterfaceWrapper) Version(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Version(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthLive operation middleware
func (siw *ServerInterfaceWrapper) HealthLive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthLive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthReady operation middleware
func (siw *ServerInterfaceWrapper) HealthReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/live", wrapper.HealthLive)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health/ready", wrapper.HealthReady)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/bootstrap/status", wrapper.BootstrapStatus)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/bootstrap", wrapper.Bootstrap)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/auth/session", wrapper.Session)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/dashboard/summary", wrapper.DashboardSummary)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/version", wrapper.Version)

	return m
}
